set_property PACKAGE_PIN Y9 [get_ports GCLK]
set_property IOSTANDARD LVCMOS33 [get_ports GCLK]
create_clock -period 10.000 -name sys_clk [get_ports GCLK]

set_property PACKAGE_PIN P16 [get_ports BTNC]
set_property IOSTANDARD LVCMOS33 [get_ports BTNC]

set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
set_property PACKAGE_PIN AA6 [get_ports AC_BCLK]
set_property PACKAGE_PIN Y6  [get_ports AC_LRCLK]
set_property PACKAGE_PIN AA7 [get_ports AC_SDATA_I]
set_property PACKAGE_PIN Y8  [get_ports AC_SDATA_O]
set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5  [get_ports AC_ADR1]
set_property PACKAGE_PIN AB4 [get_ports AC_SCL]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports {AC_MCLK AC_BCLK AC_LRCLK AC_SDATA_I AC_SDATA_O AC_ADR0 AC_ADR1 AC_SCL AC_SDA}]
set_property PULLUP true [get_ports AC_SCL]
set_property PULLUP true [get_ports AC_SDA]

set_property PACKAGE_PIN T22 [get_ports {LED[0]}]
set_property PACKAGE_PIN T21 [get_ports {LED[1]}]
set_property PACKAGE_PIN U22 [get_ports {LED[2]}]
set_property PACKAGE_PIN U21 [get_ports {LED[3]}]
set_property PACKAGE_PIN V22 [get_ports {LED[4]}]
set_property PACKAGE_PIN W22 [get_ports {LED[5]}]
set_property PACKAGE_PIN U19 [get_ports {LED[6]}]
set_property PACKAGE_PIN U14 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[*]}]

set_property PACKAGE_PIN Y11 [get_ports UART_RX]
set_property PACKAGE_PIN AA11 [get_ports UART_TX]
set_property IOSTANDARD LVCMOS33 [get_ports {UART_RX UART_TX}]
